### ISSUE TITLE
咨询一些东西

### ISSUE THREAD

**Issue by syc0000000** [Kw0k/RSSS#1]
我是大一学生，我们正在做一个项目，几乎与您的项目技术栈完全一致。
我负责Springboot后端，但是我似乎在您的仓库中没有找到后端处理摄像头视频流的方法呢。
以及想知道YOLO算法的传参是视频流还是单独的帧，我没学过机器学习，但我们项目中需要用到这个，负责这部分的同学还在学习，所以希望能直接咨询您。
我是初学者，水平不够，望谅解。

**Comment by Kw0k** [comment]
在我这个项目中我是把单帧的图片传递到后端进行识别了，你可以在OrderController.java中找到uploadImgToAddOrder方法。在这个方法中调用了DarknetUtil.IdentifyImage进行了图片的识别。DarknetUtil可以在fun/kwok/rsss/utils中找到。

**Comment by CL-CNboss** [comment]
你好，这个opencv读取那个YOLO3配置跟系统有关吗，我是mac系统，一直显示读取配置失败
