### ISSUE TITLE
咨询配置

### ISSUE THREAD

**Issue by daxiangliu** [Kw0k/RSSS#2]
OpenCV 无法解析你提供的 YOLOv3 模型配置文件 yolov3_kwok.cfg

**Comment by daxiangliu** [comment]
可以帮配置一下吗 有偿

**Comment by Kw0k** [comment]
请给我一个你的联系方式，我稍后联系你

**Comment by Kw0k** [comment]
> 可以帮配置一下吗？

请给我一个你的联系方式，我稍后联系你

**Comment by CL-CNboss** [comment]
2364354196
